services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=pgsql-saas
      - POSTGRES_USER=pgsql-saas
      - POSTGRES_PASSWORD=pgsql-saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  khairat-api:
    image: dev4w4n/emasjid-khairat-api:v2.3.1
    # build:
    #   context: ./api/khairat-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./khairat-api"]

  tabung-api:
    image: dev4w4n/emasjid-tabung-api:v2.3.1
    # build:
    #   context: ./api/tabung-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tabung-api"]

  cadangan-api:
    image: dev4w4n/emasjid-cadangan-api:v2.3.1
    # build:
    #   context: ./api/cadangan-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./cadangan-api"]

  cadangan-public-api:
    image: dev4w4n/emasjid-cadangan-public-api:v2.3.1
    # build:
    #   context: ./api/cadangan-public-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    command:
      ["./wait-for-it.sh", "saas-api:8080", "--", "./cadangan-public-api"]

  tetapan-api:
    image: dev4w4n/emasjid-tetapan-api:v2.3.1
    # build:
    #   context: ./api/tetapan-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tetapan-api"]

  tetapan-public-api:
    image: dev4w4n/emasjid-tetapan-public-api:v2.3.1
    # build:
    #   context: ./api/tetapan-public-api
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
      - GO_ENV=local
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "saas-api:8080", "--", "./tetapan-public-api"]

  dashboard:
    image: dev4w4n/emasjid-dashboard:v2.3.1
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
    ports:
      - "3000:80"
    depends_on:
      - khairat-api
      - tabung-api
      - cadangan-api
      - tetapan-api

  public-web:
    image: dev4w4n/emasjid-public-web:v2.3.1
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
    ports:
      - "3001:80"
    depends_on:
      - cadangan-public-api

  saas-api:
    image: dev4w4n/emasjid-saas:v2.3.1
    environment:
      - EMASJID_REACT_APP_BUILD_VERSION=v2.3.1
      - EMASJID_REACT_APP_DOMAIN=e-masjid.my
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./start-and-seed.sh"]

  # api-docs:
  #   build:
  #     context: ./api-docs
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - GO_ENV=local
  #   depends_on:
  #     - tabung-api
  #     - cadangan-api
  #     - cadangan-public-api
  #     - khairat-api
  #     - tetapan-api
  #     - tetapan-public-api

volumes:
  postgres_data:
