definitions:
  model.Cadangan:
    properties:
      cadanganEmail:
        type: string
      cadanganNama:
        type: string
      cadanganPhone:
        type: string
      cadanganText:
        type: string
      cadanganType:
        $ref: '#/definitions/model.CadanganType'
      createDate:
        type: integer
      id:
        type: integer
      isOpen:
        type: boolean
      score:
        type: integer
      tindakanText:
        type: string
    type: object
  model.CadanganType:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: A Cadangan service API in Go using Gin framework
  title: Cadangan Service API
  version: "1.0"
paths:
  /cadangan:
    get:
      description: Return the all  Cadangan by id.
      parameters:
      - description: cadanganTypeId
        in: query
        name: cadanganTypeId
        type: string
      - description: isOpen
        in: query
        name: isOpen
        required: true
        type: boolean
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get All Cadangan by cadanganTypeId.
      tags:
      - cadangan
    put:
      description: Save Cadangan data in Db.
      parameters:
      - description: Create Cadangan
        in: body
        name: Cadangan
        required: true
        schema:
          $ref: '#/definitions/model.Cadangan'
      produces:
      - application/json
      responses: {}
      summary: Create Cadangan
      tags:
      - cadangan
  /cadangan/{id}:
    delete:
      description: Remove Cadangandata by id.
      parameters:
      - description: delete Cadangan by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete Cadangan
      tags:
      - cadangan
    get:
      description: Return the all  Cadangan by id.
      parameters:
      - description: get cadangan by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get All Cadangan by id.
      tags:
      - cadangan
  /cadangan/count:
    get:
      description: Return Cadangan count.
      produces:
      - application/json
      responses: {}
      summary: total count of cadangan.
      tags:
      - cadangan
swagger: "2.0"
