// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kutipan": {
            "post": {
                "description": "Save kutipan data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Create kutipan",
                "parameters": [
                    {
                        "description": "Create kutipan",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Kutipan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Kutipan"
                        }
                    }
                }
            }
        },
        "/kutipan/tabung/{tabungId}": {
            "get": {
                "description": "Return the all  Kutipan by tabungId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Get All Kutipan by tabungId.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get kutipan by tabungId",
                        "name": "tabungId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Kutipan"
                            }
                        }
                    }
                }
            }
        },
        "/kutipan/tabung/{tabungId}/betweenCreateDate": {
            "get": {
                "description": "Return the all  Kutipan by tabungId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Get All Kutipan by tabungId.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get kutipan by tabungId",
                        "name": "tabungId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/kutipan/{id}": {
            "get": {
                "description": "Return the all  Kutipan by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Get All Kutipan by id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get kutipan by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Kutipan"
                        }
                    }
                }
            },
            "put": {
                "description": "Save kutipan data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Create kutipan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "update by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update kutipan",
                        "name": "kutipan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Kutipan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Kutipan"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove kutipan data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kutipan"
                ],
                "summary": "Delete kutipan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete kutipan by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tabung": {
            "get": {
                "description": "Return the all Tabung.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung"
                ],
                "summary": "Get All tabung.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tabung"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Save tabung data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung"
                ],
                "summary": "Create tabung",
                "parameters": [
                    {
                        "description": "Create Tabung",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tabung"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Tabung"
                        }
                    }
                }
            }
        },
        "/tabung-types": {
            "get": {
                "description": "Return the all Tabung type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung type"
                ],
                "summary": "Get All tabung type.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TabungType"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Save tabung type data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung type"
                ],
                "summary": "Create tabung type",
                "parameters": [
                    {
                        "description": "Create Tabung type",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TabungType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TabungType"
                        }
                    }
                }
            }
        },
        "/tabung-types/{id}": {
            "delete": {
                "description": "Remove tabung type data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung type"
                ],
                "summary": "Delete tabung type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete tabung type by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tabung/{id}": {
            "get": {
                "description": "Return the Tabung.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung"
                ],
                "summary": "Get  tabung by ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get tabung by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Tabung"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove tabung data by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabung"
                ],
                "summary": "Delete tabung",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete tabung by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.Kutipan": {
            "type": "object",
            "properties": {
                "createDate": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "tabung": {
                    "$ref": "#/definitions/model.Tabung"
                },
                "total": {
                    "type": "number"
                },
                "total100d": {
                    "type": "integer"
                },
                "total10c": {
                    "type": "integer"
                },
                "total10d": {
                    "type": "integer"
                },
                "total1c": {
                    "type": "integer"
                },
                "total1d": {
                    "type": "integer"
                },
                "total20c": {
                    "type": "integer"
                },
                "total20d": {
                    "type": "integer"
                },
                "total50c": {
                    "type": "integer"
                },
                "total50d": {
                    "type": "integer"
                },
                "total5c": {
                    "type": "integer"
                },
                "total5d": {
                    "type": "integer"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "content": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Tabung": {
            "type": "object",
            "properties": {
                "cents": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "tabungType": {
                    "$ref": "#/definitions/model.TabungType"
                }
            }
        },
        "model.TabungType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Tabung Service API",
	Description:      "A Tabung service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
