// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cadangan": {
            "post": {
                "description": "Save cadangan data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "Save cadangan",
                "parameters": [
                    {
                        "description": "Save cadangan",
                        "name": "cadangan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Cadangan"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.Cadangan": {
            "type": "object",
            "properties": {
                "cadanganEmail": {
                    "type": "string"
                },
                "cadanganNama": {
                    "type": "string"
                },
                "cadanganPhone": {
                    "type": "string"
                },
                "cadanganText": {
                    "type": "string"
                },
                "cadanganType": {
                    "$ref": "#/definitions/model.CadanganType"
                },
                "createDate": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isOpen": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "tindakanText": {
                    "type": "string"
                }
            }
        },
        "model.CadanganType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Cadangan Public Service API",
	Description:      "A Cadangan Public  service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
