// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cadangan": {
            "get": {
                "description": "Return the all  Cadangan by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "Get All Cadangan by cadanganTypeId.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cadanganTypeId",
                        "name": "cadanganTypeId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "isOpen",
                        "name": "isOpen",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "put": {
                "description": "Save Cadangan data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "Create Cadangan",
                "parameters": [
                    {
                        "description": "Create Cadangan",
                        "name": "Cadangan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Cadangan"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cadangan/count": {
            "get": {
                "description": "Return Cadangan count.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "total count of cadangan.",
                "responses": {}
            }
        },
        "/cadangan/{id}": {
            "get": {
                "description": "Return the all  Cadangan by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "Get All Cadangan by id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get cadangan by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Remove Cadangandata by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cadangan"
                ],
                "summary": "Delete Cadangan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete Cadangan by id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.Cadangan": {
            "type": "object",
            "properties": {
                "cadanganEmail": {
                    "type": "string"
                },
                "cadanganNama": {
                    "type": "string"
                },
                "cadanganPhone": {
                    "type": "string"
                },
                "cadanganText": {
                    "type": "string"
                },
                "cadanganType": {
                    "$ref": "#/definitions/model.CadanganType"
                },
                "createDate": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isOpen": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "tindakanText": {
                    "type": "string"
                }
            }
        },
        "model.CadanganType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Cadangan Service API",
	Description:      "A Cadangan service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
