definitions:
  model.Tetapan:
    properties:
      kunci:
        type: string
      nilai:
        type: string
    type: object
  model.TetapanType:
    properties:
      group_name:
        type: string
      id:
        type: integer
      int_val:
        type: integer
      str_val:
        type: string
    type: object
  model.TetapanTypeGroupNames:
    properties:
      group_names:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: A Tetapan service API in Go using Gin framework
  title: Tetapan Service API
  version: "1.0"
paths:
  /tetapan:
    get:
      description: Return  all tetapan
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Tetapan'
            type: array
      summary: find all tetapan
      tags:
      - tetapan
    post:
      description: Save tetapan data in Db.
      parameters:
      - description: Save Tetapan
        in: body
        name: tetapan
        required: true
        schema:
          $ref: '#/definitions/model.Tetapan'
      produces:
      - application/json
      responses: {}
      summary: Save tetapan
      tags:
      - tetapan
  /tetapan-types:
    get:
      description: Return  all tetapan type group names
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TetapanTypeGroupNames'
      summary: find all tetapan type group names
      tags:
      - tetapan-types
  /tetapan-types/:group_name:
    get:
      description: Return groupname by tetapan type.
      parameters:
      - description: get tetapan by group_name
        in: path
        name: group_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TetapanType'
            type: array
      summary: find groupname by tetapan type
      tags:
      - tetapan-types
  /tetapan/{kunci}:
    delete:
      description: Remove tetapan data by kunci.
      parameters:
      - description: delete tetapan by kunci
        in: path
        name: kunci
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete tetapan
      tags:
      - tetapan
    get:
      description: Return  all tetapan by kunci
      parameters:
      - description: get tetapan by kunci
        in: path
        name: kunci
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tetapan'
      summary: find tetapan by kunci
      tags:
      - tetapan
  /tetapan/senarai:
    post:
      description: BulkSave tetapan data in Db.
      parameters:
      - description: BulkSave Tetapan
        in: body
        name: tetapan
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Tetapan'
          type: array
      produces:
      - application/json
      responses: {}
      summary: BulkSave tetapan
      tags:
      - tetapan
swagger: "2.0"
