// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tetapan": {
            "get": {
                "description": "Return the all tetapan.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tetapan"
                ],
                "summary": "find all tetapan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tetapan"
                            }
                        }
                    }
                }
            }
        },
        "/tetapan/{kunci}": {
            "get": {
                "description": "Return the  tetapan by kunci",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tetapan"
                ],
                "summary": "find tetapan by kunci",
                "parameters": [
                    {
                        "type": "string",
                        "description": "kunci",
                        "name": "kunci",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Tetapan"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Tetapan": {
            "type": "object",
            "properties": {
                "kunci": {
                    "type": "string"
                },
                "nilai": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Tetapan Public Service API",
	Description:      "A Tetapan Public service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
