definitions:
  model.Tetapan:
    properties:
      kunci:
        type: string
      nilai:
        type: string
    type: object
info:
  contact: {}
  description: A Tetapan Public service API in Go using Gin framework
  title: Tetapan Public Service API
  version: "1.0"
paths:
  /tetapan:
    get:
      description: Return the all tetapan.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Tetapan'
            type: array
      summary: find all tetapan
      tags:
      - tetapan
  /tetapan/{kunci}:
    get:
      description: Return the  tetapan by kunci
      parameters:
      - description: kunci
        in: path
        name: kunci
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tetapan'
      summary: find tetapan by kunci
      tags:
      - tetapan
swagger: "2.0"
