CREATE TABLE tetapan (
    kunci VARCHAR(24) PRIMARY KEY,
    nilai VARCHAR(256)
);

INSERT INTO tetapan(kunci, nilai)
VALUES
    ('NAMA_MASJID', 'Masjid Demo'),
    ('NO_TEL_MASJID', '0123456789'),
    ('ALAMAT_MASJID', 'Jalan Masjid Demo, Desa Masjid');

CREATE TABLE tetapan_types (
    id serial PRIMARY KEY,
    group_name  VARCHAR(32),
    int_val INTEGER,
    str_val VARCHAR(128)
);

- HUBUNGAN_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('HUBUNGAN_TYPE',1,'Anak'),
    ('HUBUNGAN_TYPE',2,'Ibu'),
    ('HUBUNGAN_TYPE',3,'Ayah'),
    ('HUBUNGAN_TYPE',4,'Nenek'),
    ('HUBUNGAN_TYPE',5,'Datuk'),
    ('HUBUNGAN_TYPE',6,'Isteri'),
    ('HUBUNGAN_TYPE',7,'Suami'),
    ('HUBUNGAN_TYPE',8,'Lain-lain');

-- PENYAKIT_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('PENYAKIT_TYPE', 1, 'AIDS'),
    ('PENYAKIT_TYPE', 2, 'ALZHEIMER / ALZHEIMER''S DISEASE'),
    ('PENYAKIT_TYPE', 3, 'ANEMIA APLASTIK / APLASTIC ANAEMIA'),
    ('PENYAKIT_TYPE', 4, 'ANGIOPLASTI DAN RAWATAN INVASIF LAIN UNTUK PENYAKIT ARTERI KORONARI'),
    ('PENYAKIT_TYPE', 5, 'APNOEA TIDUR OBSTRUKTIF / OBSTRUCTIVE SLEEP APNOEA'),
    ('PENYAKIT_TYPE', 6, 'BRONKIEKTASIS / BRONCHIECTASIS'),
    ('PENYAKIT_TYPE', 7, 'BUTA / BLINDNESS'),
    ('PENYAKIT_TYPE', 8, 'DISTROFI OTOT / MUSCULAR DYSTROPHY'),
    ('PENYAKIT_TYPE', 9, 'ABNORMALITI URINARI KONGENITAL / CONGENITAL URINARY ABNORMALITIES'),
    ('PENYAKIT_TYPE', 10, 'ENSEFALITIS / ENCEPHALITIS'),
    ('PENYAKIT_TYPE', 11, 'FIBROSIS PARU-PARU / LUNG FIBROSIS'),
    ('PENYAKIT_TYPE', 12, 'HEPATITIS VIRUS FULMINAN / FULMINANT VIRAL HEPATITIS'),
    ('PENYAKIT_TYPE', 13, 'HILANG KEBELEHAN BERTUTUR / LOSS OF SPEECH'),
    ('PENYAKIT_TYPE', 14, 'HILANG UPAYA KEKAL / TOTAL PERMANENT DISABILITY'),
    ('PENYAKIT_TYPE', 15, 'HIPERTENSI ARTERI PULMONARI PRIMER'),
    ('PENYAKIT_TYPE', 16, 'HIPERTENSI PULMONARI SEKUNDER / SECONDARY PULMONARY HYPERTENSION'),
    ('PENYAKIT_TYPE', 17, 'HIV (VIRUS KURANG DAYA TAHAN MANUSIA)'),
    ('PENYAKIT_TYPE', 18, 'KANSER / CANCER'),
    ('PENYAKIT_TYPE', 19, 'KARDIOMIOPATI / CARDIOMYOPATHY'),
    ('PENYAKIT_TYPE', 20, 'KECACATAN INTELEKTUAL DISEBABKAN KEMALANGAN ATAU PENYAKIT / INTELLECTUAL IMPAIRMENT DUE TO ACCIDENT OR SICKNESS'),
    ('PENYAKIT_TYPE', 21, 'KECEDERAAN ACL'),
    ('PENYAKIT_TYPE', 22, 'KEGAGALAN BUAH PINGGANG / KIDNEY FAILURE'),
    ('PENYAKIT_TYPE', 23, 'KEHILANGAN UPAYA HIDUP SENDIRI / LOSS OF INDEPENDENT EXISTENCE'),
    ('PENYAKIT_TYPE', 24, 'KELECURN PARAH / MAJOR BURNS'),
    ('PENYAKIT_TYPE', 25, 'KELECURN TAHAP KETIGA'),
    ('PENYAKIT_TYPE', 26, 'KELUMPUHAN / PARALYSIS'),
    ('PENYAKIT_TYPE', 27, 'KEMURUNGAN MAJOR / MAJOR DEPRESSION'),
    ('PENYAKIT_TYPE', 28, 'KOMA / COMA'),
    ('PENYAKIT_TYPE', 29, 'LELAH/ASMA YANG TERUK / SEVERE ASTHMA'),
    ('PENYAKIT_TYPE', 30, 'LEUKIMIA / LEUKAEMIA'),
    ('PENYAKIT_TYPE', 31, 'LIMFOMA / LYMPHOMA'),
    ('PENYAKIT_TYPE', 32, 'LUPUS ERITEMATOSUS SISTEMIK DENGAN BUAH PINGGANG YANG TERUK'),
    ('PENYAKIT_TYPE', 33, 'MENINGITIS / MENINGITIS'),
    ('PENYAKIT_TYPE', 34, 'MOOD BIPOLAR / BIPOLAR MOOD'),
    ('PENYAKIT_TYPE', 35, 'PANKREATITIS KRONIK BERULANG'),
    ('PENYAKIT_TYPE', 36, 'PEKAK / DEAFNESS'),
    ('PENYAKIT_TYPE', 37, 'PEMBEDAHA AORTA / SURGERY TO AORTA'),
    ('PENYAKIT_TYPE', 38, 'PEMBEDAHA OTAK'),
    ('PENYAKIT_TYPE', 39, 'PEMBEDAHA PINTASAN ARTERI KORONARI'),
    ('PENYAKIT_TYPE', 40, 'PEMINDAHAN ORGAN UTAMA / MAJOR ORGAN TRANSPLANT'),
    ('PENYAKIT_TYPE', 41, 'PEMINDAHAN SEL STEM HEMATOPOETIK / HEMATOPOETIC STEM CELL TRANSPLANTATION'),
    ('PENYAKIT_TYPE', 42, 'PENGGANTIAN INJAP JANTUNG / HEART VALVE REPLACEMENT'),
    ('PENYAKIT_TYPE', 43, 'PENYAKIT ARTERI KORONARI / CORONARY ARTERY DISEASE'),
    ('PENYAKIT_TYPE', 44, 'PENYAKIT HATI KRONIK / CHRONIC LIVER DISEASE'),
    ('PENYAKIT_TYPE', 45, 'PENYAKIT MEDULARI SISTIK / MEDULLARY CYSTIC DISEASE'),
    ('PENYAKIT_TYPE', 46, 'PENYAKIT MEMBAWA MAUT / TERMINAL ILLNESS'),
    ('PENYAKIT_TYPE', 47, 'PENYAKIT NEURON MOTOR / MOTOR NEURONE DISEASE'),
    ('PENYAKIT_TYPE', 48, 'PENYAKIT PARKINSON / PARKINSON''S DISEASE'),
    ('PENYAKIT_TYPE', 49, 'PENYAKIT PARU-PARU KRONIK / CHRONIC LUNG DISEASE'),
    ('PENYAKIT_TYPE', 50, 'PENYAKIT PULMONARI OBSTRUKTIF KRONIK TERUK (COPD) / EMFISEMA / SEVERE CHRONIC OBSTRUCTIVE PULMONARY DISEASE(COPD) / EMPHYSEMA'),
    ('PENYAKIT_TYPE', 51, 'PENYAKIT RADANG USUS KRONIK / CHRONIC INFLAMMATORY BOWEL DISEASE'),
    ('PENYAKIT_TYPE', 52, 'PENYAKIT SISTIK MEDULAR'),
    ('PENYAKIT_TYPE', 53, 'PENYAKIT TERMINAL (MEMBAWA MAUT)'),
    ('PENYAKIT_TYPE', 54, 'POLIOMIELITIS / POLIOMYELITIS'),
    ('PENYAKIT_TYPE', 55, 'PULMONARI PRIMER / PRIMARY PULMONARY'),
    ('PENYAKIT_TYPE', 56, 'SERANGAN PENYAKIT JANTUNG / HEART ATTACK'),
    ('PENYAKIT_TYPE', 57, 'SINDROM APALIK / APPALIC SYNDROME'),
    ('PENYAKIT_TYPE', 58, 'SISTEMIK LUPUS ERITEMATOSUS (SLE) DENGAN LUPUS NEPHRITIS / SYSTEMIC LUPUS ERITEMATOSUS (SLE) WITH LUPUS NEPHRITIS 2'),
    ('PENYAKIT_TYPE', 59, 'SKIZOFRENIA / SCHIZOPHRENIA'),
    ('PENYAKIT_TYPE', 60, 'SKLERODERMA PROGRESIF'),
    ('PENYAKIT_TYPE', 61, 'SKLEROSIS BERGANDA / MULTIPLE SCLEROSIS'),
    ('PENYAKIT_TYPE', 62, 'SKLEROSIS SISTEMIK DENGAN HIPERTENSI PULMONARI / SYSTEMIC SCLEROSIS WITH PULMONARY HYPERTENSION'),
    ('PENYAKIT_TYPE', 63, 'STROK/ANGIN AHMAR / STROKE'),
    ('PENYAKIT_TYPE', 64, 'TALESEMIA MAJOR / THALASSAEMIA MAJOR'),
    ('PENYAKIT_TYPE', 65, 'TRANSPALN ORGAN UTAMA / SUMSUM TULANG'),
    ('PENYAKIT_TYPE', 66, 'TRAUMA UTAMA DI KEPALA / MAJOR HEAD TRAUMA'),
    ('PENYAKIT_TYPE', 67, 'TUMOR OTAK BENIGNA / BENIGN TUMOUR OF THE BRAIN'),
    ('PENYAKIT_TYPE', 68, 'LAIN-LAIN PENYAKIT / KECEDEERAAN KRONIK'),
    ('PENYAKIT_TYPE', 69, 'KENCING MANIS / DIABETES');


-- BANTUAN_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('BANTUAN_TYPE',1,'ZAKAT'),
    ('BANTUAN_TYPE',2,'JKM'),
    ('BANTUAN_TYPE',3,'NGO');

-- NEGERI_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('NEGERI_TYPE', 1, 'JOHOR'),
    ('NEGERI_TYPE', 2, 'KEDAH'),
    ('NEGERI_TYPE', 3, 'KELANTAN'),
    ('NEGERI_TYPE', 4, 'MELAKA'),
    ('NEGERI_TYPE', 5, 'NEGERI SEMBILAN'),
    ('NEGERI_TYPE', 6, 'PAHANG'),
    ('NEGERI_TYPE', 7, 'PERAK'),
    ('NEGERI_TYPE', 8, 'PERLIS'),
    ('NEGERI_TYPE', 9, 'PULAU PINANG'),
    ('NEGERI_TYPE', 10, 'SABAH'),
    ('NEGERI_TYPE', 11, 'SARAWAK'),
    ('NEGERI_TYPE', 12, 'SELANGOR'),
    ('NEGERI_TYPE', 13, 'TERENGGANU'),
    ('NEGERI_TYPE', 14, 'WP KUALA LUMPUR'),
    ('NEGERI_TYPE', 15, 'WP LABUAN'),
    ('NEGERI_TYPE', 16, 'WP PUTRAJAYA');

-- JANTINA_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('JANTINA_TYPE',1,'LELAKI'),
    ('JANTINA_TYPE',2,'PEREMPUAN');

-- BANGSA_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('BANGSA_TYPE',1,'MELAYU'),
    ('BANGSA_TYPE',2,'CINA');
    ('BANGSA_TYPE',3,'INDIA');
    ('BANGSA_TYPE',4,'LAIN-LAIN');

-- KAHWIN_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('KAHWIN_TYPE',1,'BUJANG'),
    ('KAHWIN_TYPE',2,'BERKAHWIN'),
    ('KAHWIN_TYPE',3,'DUDA'),
    ('KAHWIN_TYPE',4,'JANDA'),

-- KERJA_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('KERJA_TYPE',1,'KERAJAAN'),
    ('KERJA_TYPE',2,'SWASTA'),
    ('KERJA_TYPE',3,'SENDIRI'),
    ('KERJA_TYPE',4,'PENCEN'),
    ('KERJA_TYPE',5,'SURI RUMAH'),
    ('KERJA_TYPE',6,'PELAJAR'),
    ('KERJA_TYPE',7,'TIDAK BEKERJA'),

-- ISIRUMAH_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('ISIRUMAH_TYPE',1,'0 - 1000'),
    ('ISIRUMAH_TYPE',2,'1000 - 2000'),
    ('ISIRUMAH_TYPE',3,'2000 - 3000'),
    ('ISIRUMAH_TYPE',4,'3000 - 4000'),
    ('ISIRUMAH_TYPE',5,'LEBIH DARI 4000'),

-- OKU_TYPE
INSERT INTO tetapan_types (group_name, int_val, str_val)
VALUES
    ('OKU_TYPE',1,'KURANG UPAYA PENDENGARAN'),
    ('OKU_TYPE',2,'KURANG UPAYA FIZIKAL'),
    ('OKU_TYPE',3,'KURANG UPAYA PELBAGAI'),
    ('OKU_TYPE',4,'KURANG UPAYA PENGLIHATAN'),
    ('OKU_TYPE',5,'KURANG UPAYA PEMBELAJARAN'),
    ('OKU_TYPE',6,'KURANG UPAYA PERTUTURAN'),
    ('OKU_TYPE',7,'KURANG UPAYA MENTAL'),
    ('OKU_TYPE',8,'LAIN-LAIN KURANG UPAYA'),